config/routes.rb
Rails.application.routes.draw do  
  devise_for :users
  root to: "home#index"
  resources :users, only:[:index, :show, :edit, :update]
  resources :posts do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  attachment :image

  with_options presence: true do
    validates :title
    validates :body
    validates :image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth 
  private
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == "admin" && password == "2222"
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      @post = @comment.post
      @comments = @post.comments
      render "posts/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit
    @post = Post.find(params[:id])
    unless current_user == @post.user
      redirect_to posts_path, alert: '不正なアクセスです'
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    if @post.save
      redirect_to post_path(@post), notice: '更新に成功しました'
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_path(post.user)
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to posts_path, alert: '不正なアクセスです'
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to user_path(@user), notice: '更新に成功しました'
    else
      render :edit
    end
  end

private
  def user_params
    params.require(:user).permit(:nickname, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="is-size-1" style="font-family: fantasy;">cookshare</strong> 
        </p>
      </div>
      <% if user_signed_in? %>
        <div class="content has-text-centered">
        <p>
          <strong class="is-size-1" style="font-family: fantasy;">Hello  Word!</strong> 
        </p>
        </div>
      <% else %>
        <div class="columns is-centered">
          <div class="column is-5">
            <br>
            <%= link_to "ログイン", new_user_session_path, class: "button is-danger is-fullwidth" %>
            <br>
            <%= link_to "新規登録", new_user_registration_path, class: "button is-danger is-fullwidth" %>
          </div>
        <% end %>
      </div>
    </div>
  </article>
  <br>
<div class="columns is-centered">
  <div class="column">
    <div class="slide" id="makeImg">
      <%= image_tag "cook.jpg", class:"cook" %>
      
      <%= image_tag "cook02.jpg", class:"cook" %>
      
      <%= image_tag "cook03.jpg", class:"cook" %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookshare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-danger">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family :fantasy;">cookshare</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>


    <% if user_signed_in? %>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-item">
          <%= link_to "レシピ一覧", posts_path, class: "navbar-item button is-danger is-light" %>
        </div>
        <div class="navbar-item">
          <%= link_to "レシピ投稿", new_post_path, class: "navbar-item button is-danger is-light" %>
        </div>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "マイページ", user_path(current_user), class: "button is-danger is-light" %>
                </p>
                <p class="control">
                  <%= link_to "ユーザー一覧", users_path, class: "button is-danger is-light" %>
                </p>
                <p class="control">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-danger is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
    <% else %>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-item">
          <%= link_to "レシピ一覧", posts_path, class: "button is-danger is-light" %>
        </div>
        <div class="navbar-item">
          <%= link_to "ユーザー一覧", users_path, class: "button is-danger is-light" %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "ログイン", new_user_session_path, class: "button is-danger is-light" %>
              </p>
              <p class="control">
                <%= link_to "新規登録", new_user_registration_path, class: "button is-danger is-light" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
 <section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title" >レシピ編集</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="columns is-6">
        <%= form_with model: @post, local: true do |f| %>
          <%= render 'shared/error_messages', model: f.object %>
          
          <div class="field">
            <%= f.label :title, "レシピ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "作り方", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/index.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title" >レシピ一覧</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @posts.each do |post|%>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to post_path(post) do %>
                  <%= attachment_image_tag post, :image %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= link_to user_path(post.user.id) do%>
                      <%= attachment_image_tag post.user, :profile_image, fallback: "no-image.jpg", class: "profile_image" %>
                    <% end %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%= link_to post.user.nickname, user_path(post.user) %></div>
                </div>
              </div>

              <div class="content">
                <time><%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>  
      <% end %>
    </div>
  </div>
</section>

                

app/views/posts/new.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title" >新規レシピ一覧</h1>
    </div>
  </div>
</section>


<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @post, local: true do |f| %>
          <%= render 'shared/error_messages', model: f.object %>

          <div class="field">
            <%= f.label :titile, "レシピ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "作り方", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit "投稿", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title" >レシピ詳細</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @post, :image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @post.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>レシピ</th>
                </tr>
                <tr>
                  <th><%= simple_format @post.body %></th>
                </tr>
              </table>
              <% if @post.user.id == current_user.id %>
              <%= link_to "編集画面へ", edit_post_path(@post), class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
            By <%= @post.user.nickname %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @post.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@post.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @post.user.nickname %> さんのページへ
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <ul class="comments_lists">
        <% if @comments %>
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.text%>
              <%= link_to "#{comment.user.nickname}", "/users/#{comment.user.id}", class: :comment_user %>
            </li>
          <% end %>
        <% end %>
        </ul>
        <% if user_signed_in? %>
          <%= form_with(model: [@post, @comment], local: true) do |f| %>

            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text, id:"comment_text", class:"input is-warning" %>
            </div>
            <div class="actions">
              <%= f.submit "送信", class: "button is-success" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="notification is-danger">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/edit.html.erb
 <section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title" >ユーザー編集</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="columns is-6">
        <%= form_with model: @user, local: true do |f| %>
          <%= render 'shared/error_messages', model: f.object %>
          
          <div class="field">
            <%= f.label :nickname, "ニックネーム", class: "label" %>
            <%= f.text_field :nickname, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.text_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "保存", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title" >クックシェア一覧</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class ="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, fallback: "no-image.jpg" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.nickname, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数:<%= user.posts.count %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title" >マイページ</h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.jpg", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.nickname %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td>
                  <%= @user.email %>
                </td>
                <td>
                  <%= link_to "編集", edit_user_path(@user), class: "buttton is-primary" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile%>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.posts.each do |post| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to post_path(post) do %>
                  <%= attachment_image_tag post, :image, fallback: "no-image.jpg" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to post_path(post), class: "penel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                  このレシピを見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_post_path(post), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      このレシピを編集する
                    <% end %>
                    <%= link_to post_path(post), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      このレシピを削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>